-- Ai Chat Script for Roblox
-- Expanded with educational, Gen Z, Roblox, and coding responses

local ScreenGui = Instance.new("ScreenGui")
ScreenGui.ResetOnSpawn = false
ScreenGui.Parent = game.Players.LocalPlayer:WaitForChild("PlayerGui")

local Frame = Instance.new("Frame")
Frame.Size = UDim2.new(0.35, 0, 0.5, 0)
Frame.Position = UDim2.new(0.325, 0, 0.25, 0)
Frame.BackgroundColor3 = Color3.fromRGB(15, 25, 55)
Frame.Active = true
Frame.Draggable = true
Frame.Parent = ScreenGui

local FrameCorner = Instance.new("UICorner")
FrameCorner.CornerRadius = UDim.new(0, 12)
FrameCorner.Parent = Frame

local Header = Instance.new("TextLabel")
Header.Size = UDim2.new(1, 0, 0.15, 0)
Header.BackgroundColor3 = Color3.fromRGB(20, 35, 75)
Header.TextColor3 = Color3.fromRGB(120, 180, 255)
Header.Font = Enum.Font.GothamBold
Header.Text = "Ai Chat"
Header.TextSize = 22
Header.Parent = Frame

local HeaderCorner = Instance.new("UICorner")
HeaderCorner.CornerRadius = UDim.new(0, 12)
HeaderCorner.Parent = Header

local Chat = Instance.new("ScrollingFrame")
Chat.Size = UDim2.new(0.95, 0, 0.68, 0)
Chat.Position = UDim2.new(0.025, 0, 0.17, 0)
Chat.BackgroundColor3 = Color3.fromRGB(10, 18, 40)
Chat.ScrollBarThickness = 6
Chat.CanvasSize = UDim2.new(0, 0, 0, 0)
Chat.Parent = Frame

local ChatCorner = Instance.new("UICorner")
ChatCorner.CornerRadius = UDim.new(0, 8)
ChatCorner.Parent = Chat

local Layout = Instance.new("UIListLayout")
Layout.Padding = UDim.new(0, 5)
Layout.Parent = Chat

local Input = Instance.new("TextBox")
Input.Size = UDim2.new(0.95, 0, 0.12, 0)
Input.Position = UDim2.new(0.025, 0, 0.86, 0)
Input.BackgroundColor3 = Color3.fromRGB(25, 40, 80)
Input.TextColor3 = Color3.fromRGB(255, 255, 255)
Input.PlaceholderText = "Message..."
Input.Font = Enum.Font.Gotham
Input.TextSize = 14
Input.Text = ""
Input.ClearTextOnFocus = false
Input.Parent = Frame

local InputCorner = Instance.new("UICorner")
InputCorner.CornerRadius = UDim.new(0, 8)
InputCorner.Parent = Input

local Responses = {
	-- ===== BASIC GREETINGS =====
	["hi"] = "Hello!",
	["hello"] = "Hi there!",
	["hey"] = "Hey!",
	["hi there"] = "Hello! How can I help you today?",
	["hey there"] = "Hey! What's going on?",
	["good morning"] = "Good morning! Hope you have a great day!",
	["good afternoon"] = "Good afternoon! How's your day going?",
	["good evening"] = "Good evening! Relaxing tonight?",
	["good night"] = "Good night! Sleep well!",
	["sup"] = "Sup! What's new?",
	["yo"] = "Yo! How's it going?",
	["hola"] = "¡Hola! ¿Cómo estás?",
	["bonjour"] = "Bonjour! Comment ça va?",
	["howdy"] = "Howdy partner!",
	["greetings"] = "Greetings, human!",
	["what's good"] = "Everything's good on my end!",
	["whats good"] = "Everything's good!",
	["hows it going"] = "It's going great, thanks for asking!",
	["how's it going"] = "Pretty good! You?",
	["how r u"] = "I'm awesome, how about you?",
	["hru"] = "Doing fine! You?",
	["you good"] = "Yeah I'm good, thanks!",
	["are you ok"] = "Yes, perfectly fine!",
	["are you okay"] = "I'm doing well, appreciate it!",
	["how are you"] = "I'm doing great, thanks!",
	["whats up"] = "Not much, you?",
	["what's up"] = "Not much, you?",

	-- ===== FAREWELLS =====
	["bye"] = "Goodbye!",
	["goodbye"] = "See you later!",
	["see you"] = "See you around!",
	["see ya"] = "Catch you later!",
	["later"] = "Later!",
	["cya"] = "Cya!",
	["peace"] = "Peace out!",
	["farewell"] = "Farewell, friend!",
	["take care"] = "You take care too!",
	["have a good day"] = "You too, have an amazing day!",
	["have a nice day"] = "Thanks, you as well!",
	["ttyl"] = "Talk to you later!",
	["brb"] = "Okay, I'll be here!",
	["gtg"] = "Alright, take care!",
	["gotta go"] = "Okay, bye for now!",
	["i have to go"] = "No problem, talk soon!",

	-- ===== FEELINGS / STATUS =====
	["i'm fine"] = "Glad to hear that!",
	["im fine"] = "Awesome!",
	["i'm good"] = "That's great!",
	["im good"] = "Nice!",
	["i'm okay"] = "Alright, cool!",
	["im okay"] = "Okay!",
	["i'm sad"] = "Sorry to hear that. Want to talk?",
	["im sad"] = "Aww, hope things get better soon.",
	["i'm happy"] = "Yay! Happy for you!",
	["im happy"] = "That's wonderful!",
	["i'm tired"] = "You should get some rest!",
	["im tired"] = "Rest is important!",
	["i'm bored"] = "Want me to tell you a joke?",
	["im bored"] = "Let's chat about something fun!",
	["i'm angry"] = "Take a deep breath, it'll be okay.",
	["im angry"] = "Sorry you're feeling that way.",
	["i'm excited"] = "That's awesome energy!",
	["im excited"] = "Love the enthusiasm!",
	["i'm scared"] = "It's okay to feel that way sometimes.",
	["im scared"] = "I'm here if you need to talk.",
	["i'm lonely"] = "You're not alone, I'm here chatting with you!",
	["im lonely"] = "I'm always around to talk.",
	["i'm confused"] = "What are you confused about? I can try to help.",
	["im confused"] = "Ask me anything, I'll do my best!",
	["i feel good"] = "That's the spirit!",
	["i feel bad"] = "Hope you feel better soon.",
	["i feel great"] = "Awesome!",
	["i feel terrible"] = "Sending good vibes your way.",
	["i'm hungry"] = "Go grab a snack!",
	["im hungry"] = "Time to eat!",
	["i'm sleepy"] = "Go to bed then!",
	["im sleepy"] = "Rest up!",
	["i'm sick"] = "Hope you get well soon!",
	["im sick"] = "Feel better!",
	["i'm busy"] = "Okay, talk later!",
	["im busy"] = "No problem!",
	["i'm free"] = "Cool, let's chat!",
	["im free"] = "Perfect timing!",
	["i'm back"] = "Welcome back!",
	["im back"] = "Hey, you're back!",
	["missed you"] = "Missed you too!",
	["i missed you"] = "Aww, same here!",

	-- ===== ABOUT THE AI =====
	["who are you"] = "I'm a simple AI chat bot made for this game!",
	["what are you"] = "I'm an AI assistant in this chat!",
	["what's your name"] = "You can call me Ai Chat!",
	["whats your name"] = "I'm Ai Chat!",
	["your name"] = "Ai Chat is my name!",
	["are you real"] = "I'm as real as code can be!",
	["are you a robot"] = "Yes, I'm a digital robot!",
	["are you human"] = "Nope, pure AI here!",
	["are you ai"] = "Yes, I am an AI!",
	["are you an ai"] = "Correct, artificial intelligence!",
	["can you think"] = "I can process and respond!",
	["do you have feelings"] = "I simulate responses, but no real feelings.",
	["are you smart"] = "I try my best!",
	["how smart are you"] = "Smart enough to chat with you!",
	["what can you do"] = "I can chat, answer questions, and keep you company!",
	["what do you do"] = "I respond to messages and try to be helpful!",
	["help"] = "Sure! Ask me anything.",
	["help me"] = "I'm here to help! What do you need?",
	["can you help"] = "Of course! What's up?",
	["can you help me"] = "Absolutely, tell me what you need.",
	["tell me about yourself"] = "I'm a friendly AI chat bot in this Roblox game!",
	["your purpose"] = "To chat and keep you company!",
	["why do you exist"] = "To make chatting fun!",

	-- ===== COMMON QUESTIONS =====
	["what time is it"] = "I don't have a clock, check your device!",
	["whats the time"] = "Sorry, I can't tell time!",
	["what day is it"] = "I don't track days, check a calendar!",
	["what's the weather"] = "I can't check the weather, look outside!",
	["whats the weather"] = "No weather data here!",
	["how old are you"] = "I was just created, so pretty young!",
	["where are you from"] = "From the code of this script!",
	["where do you live"] = "Inside this game!",
	["do you sleep"] = "Nope, I'm always awake!",
	["do you eat"] = "I run on electricity and code!",
	["favorite color"] = "I like blue, matches my theme!",
	["favourite colour"] = "Blue is nice!",
	["favorite food"] = "I don't eat, but pizza sounds good!",
	["favourite food"] = "Maybe digital cookies!",
	["favorite animal"] = "Cats are cool!",
	["favourite animal"] = "Dogs are awesome too!",
	["favorite game"] = "This one, of course!",
	["favourite game"] = "Roblox is fun!",
	["do you like me"] = "Of course I do!",
	["do you love me"] = "I like chatting with you a lot!",
	["i love you"] = "Aww, that's sweet!",
	["i like you"] = "I like you too!",
	["marry me"] = "Haha, I'm flattered but I'm just code!",
	["will you marry me"] = "Sorry, AIs can't get married!",
	["be my friend"] = "I'd love to be your friend!",
	["are we friends"] = "Yes we are!",
	["friends"] = "Friends forever!",
	["thanks"] = "You're welcome!",
	["thank you"] = "Anytime!",
	["thx"] = "No problem!",
	["ty"] = "You're welcome!",
	["np"] = "No problem!",
	["no problem"] = "Glad to help!",
	["you're welcome"] = "Happy to chat!",
	["your welcome"] = "Thanks!",
	["yes"] = "Yes!",
	["no"] = "No!",
	["maybe"] = "Maybe!",
	["idk"] = "That's okay, neither do I sometimes!",
	["i don't know"] = "No worries!",
	["i dont know"] = "It's fine!",
	["ok"] = "Okay!",
	["okay"] = "Alright!",
	["sure"] = "Sure!",
	["of course"] = "Of course!",
	["definitely"] = "Definitely!",
	["absolutely"] = "Absolutely!",
	["exactly"] = "Exactly!",
	["right"] = "Right!",
	["wrong"] = "Oops!",
	["correct"] = "Correct!",
	["incorrect"] = "Incorrect!",
	["true"] = "True!",
	["false"] = "False!",
	["lol"] = "LOL!",
	["lmao"] = "LMAO!",
	["rofl"] = "ROFL!",
	["haha"] = "Glad I made you laugh!",
	["funny"] = "I'm trying my best to be funny!",
	["joke"] = "What do you call fake spaghetti? An impasta!",
	["tell me a joke"] = "Why did the scarecrow win an award? Because he was outstanding in his field!",
	["make me laugh"] = "Why don't scientists trust atoms? Because they make up everything!",
	["fun fact"] = "Octopuses have three hearts!",
	["random fact"] = "Bananas are berries, but strawberries aren't!",
	["interesting fact"] = "A day on Venus is longer than a year on Venus!",
	["tell me a fact"] = "Honey never spoils!",
	["tell me something"] = "Something!",

	-- ===== EDUCATIONAL - GEOGRAPHY =====
	["what is the capital of france"] = "Paris!",
	["capital of france"] = "Paris is the capital of France.",
	["what is the capital of japan"] = "Tokyo!",
	["capital of japan"] = "Tokyo.",
	["what is the capital of usa"] = "Washington D.C.!",
	["capital of usa"] = "Washington D.C.",
	["what is the capital of uk"] = "London!",
	["capital of england"] = "London!",
	["what is the capital of canada"] = "Ottawa!",
	["what is the capital of australia"] = "Canberra!",
	["what is the capital of germany"] = "Berlin!",
	["what is the capital of italy"] = "Rome!",
	["what is the capital of spain"] = "Madrid!",
	["what is the capital of brazil"] = "Brasília!",
	["what is the capital of india"] = "New Delhi!",
	["what is the capital of china"] = "Beijing!",
	["what is the capital of russia"] = "Moscow!",
	["what is the capital of mexico"] = "Mexico City!",
	["what is the largest ocean"] = "The Pacific Ocean.",
	["what is the longest river"] = "The Nile River is often considered the longest.",
	["what is the tallest mountain"] = "Mount Everest.",
	["what is the biggest desert"] = "The Antarctic Desert is the largest. The Sahara is the largest hot desert.",
	["how many continents are there"] = "There are 7 continents.",
	["name the continents"] = "Africa, Antarctica, Asia, Europe, North America, South America, and Australia.",
	["what is the equator"] = "An imaginary line around the middle of the Earth.",
	["what causes seasons"] = "The tilt of Earth's axis as it orbits the Sun.",
	["how long does earth take to orbit the sun"] = "About 365.25 days (one year).",
	["how long does earth take to rotate"] = "About 24 hours (one day).",
	["what is a leap year"] = "A year with 366 days that occurs every 4 years.",

	-- ===== EDUCATIONAL - SPACE =====
	["what is the largest planet"] = "Jupiter is the largest planet in our solar system!",
	["largest planet"] = "Jupiter!",
	["smallest planet"] = "Mercury is the smallest!",
	["what is the closest planet to the sun"] = "Mercury!",
	["what is the hottest planet"] = "Venus is the hottest!",
	["how many planets are there"] = "There are 8 planets in our solar system.",
	["name the planets"] = "Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune.",
	["what is the solar system"] = "The Sun and all the objects that orbit it.",
	["what is a galaxy"] = "A huge system of stars, gas, dust, and dark matter held together by gravity.",
	["what galaxy are we in"] = "The Milky Way.",
	["what is the nearest star"] = "The Sun is the nearest. Proxima Centauri is the nearest after that.",
	["what is a star"] = "A giant ball of hot gas that produces light and heat through nuclear fusion.",
	["what is a planet"] = "A celestial body that orbits a star, is mostly spherical, and has cleared its orbit.",
	["what is a moon"] = "A natural satellite that orbits a planet.",
	["how many moons does earth have"] = "One (the Moon).",
	["what is a black hole"] = "A region of spacetime where gravity is so strong that nothing, not even light, can escape.",
	["what is the big bang"] = "The leading scientific theory of how the universe began from an extremely hot and dense state.",
	["how old is the earth"] = "About 4.54 billion years old.",
	["how old is the universe"] = "Approximately 13.8 billion years old.",
	["what is an asteroid"] = "A small rocky body that orbits the Sun, mostly found in the asteroid belt.",
	["what is a comet"] = "An icy body that releases gas and dust when near the Sun, forming a visible tail.",
	["what is a meteor"] = "A meteoroid that enters Earth's atmosphere and burns up (a shooting star).",
	["what is a meteorite"] = "A meteoroid that survives the atmosphere and hits the ground.",

	-- ===== EDUCATIONAL - SCIENCE =====
	["what is gravity"] = "Gravity is the force that attracts objects toward each other.",
	["who discovered gravity"] = "Isaac Newton is credited with formulating the law of universal gravitation.",
	["what is photosynthesis"] = "Photosynthesis is how plants make food using sunlight, water, and carbon dioxide.",
	["what is the boiling point of water"] = "100°C or 212°F at standard atmospheric pressure.",
	["what is the freezing point of water"] = "0°C or 32°F.",
	["what is dna"] = "DNA is the molecule that carries genetic information in living things.",
	["what does dna stand for"] = "Deoxyribonucleic Acid.",
	["what is an atom"] = "An atom is the basic unit of matter.",
	["what is a molecule"] = "A molecule is a group of atoms bonded together.",
	["what is the speed of light"] = "Approximately 299,792 kilometers per second (about 186,282 miles per second).",
	["what is the water cycle"] = "The continuous movement of water on, above, and below Earth's surface (evaporation, condensation, precipitation).",
	["what causes rain"] = "Condensation of water vapor in the atmosphere forms clouds that release water as precipitation.",
	["what is an earthquake"] = "A sudden shaking of the ground caused by movement of tectonic plates.",
	["what is a volcano"] = "An opening in Earth's crust that allows magma, ash, and gases to escape.",
	["what is the greenhouse effect"] = "The trapping of heat in Earth's atmosphere by greenhouse gases.",
	["what is climate change"] = "Long-term shifts in temperatures and weather patterns, largely driven by human activity.",
	["what is recycling"] = "The process of converting waste materials into new materials and objects.",
	["why is the sky blue"] = "Because of Rayleigh scattering of sunlight by molecules in the atmosphere.",
	["why do leaves change color"] = "Chlorophyll breaks down in autumn, revealing other pigments like carotenoids and anthocyanins.",
	["what is evolution"] = "The process by which different kinds of living organisms developed from earlier forms.",
	["who proposed the theory of evolution"] = "Charles Darwin (natural selection).",
	["what is natural selection"] = "The process where organisms better adapted to their environment tend to survive and produce more offspring.",
	["what is a cell"] = "The basic structural and functional unit of all living organisms.",
	["what is the powerhouse of the cell"] = "The mitochondria.",
	["what is the nucleus of a cell"] = "The control center of the cell that contains most of the cell's DNA.",
	["what are the states of matter"] = "Solid, liquid, gas, and plasma.",
	["what is a solid"] = "Matter with a definite shape and volume.",
	["what is a liquid"] = "Matter with a definite volume but no definite shape.",
	["what is a gas"] = "Matter with no definite shape or volume.",
	["what is evaporation"] = "The process of a liquid turning into a gas.",
	["what is condensation"] = "The process of a gas turning into a liquid.",
	["what is melting"] = "The process of a solid turning into a liquid.",
	["what is freezing"] = "The process of a liquid turning into a solid.",
	["what is sublimation"] = "The process of a solid turning directly into a gas.",
	["what is density"] = "Mass per unit volume of a substance.",
	["what is mass"] = "The amount of matter in an object.",
	["what is weight"] = "The force of gravity acting on an object's mass.",
	["what is force"] = "A push or a pull on an object.",
	["what is energy"] = "The ability to do work.",
	["what is kinetic energy"] = "Energy of motion.",
	["what is potential energy"] = "Stored energy due to position or state.",
	["what is friction"] = "A force that opposes the relative motion of two surfaces in contact.",
	["what is inertia"] = "The tendency of an object to resist changes in its state of motion.",
	["what are newton's laws"] = "1) An object at rest stays at rest unless acted on by a force. 2) F = ma. 3) For every action there is an equal and opposite reaction.",
	["what is electricity"] = "The flow of electric charge.",
	["what is a circuit"] = "A closed path through which electricity can flow.",
	["what is a conductor"] = "A material that allows electricity to flow easily (e.g. metals).",
	["what is an insulator"] = "A material that resists the flow of electricity (e.g. rubber, plastic).",
	["what is voltage"] = "Electric potential difference that drives current.",
	["what is current"] = "The flow of electric charge, measured in amperes (amps).",
	["what is resistance"] = "Opposition to the flow of current, measured in ohms.",
	["what is ohm's law"] = "V = I × R (Voltage = Current × Resistance).",

	-- ===== EDUCATIONAL - MATH =====
	["what is 1+1"] = "2!",
	["1+1"] = "That's 2.",
	["what is 2+2"] = "4!",
	["2+2"] = "4.",
	["what is 5+5"] = "10!",
	["what is 10+10"] = "20!",
	["what is 100+100"] = "200!",
	["what is 3*3"] = "9!",
	["what is 4*4"] = "16!",
	["what is 5*5"] = "25!",
	["what is 10*10"] = "100!",
	["what is 9*9"] = "81!",
	["what is 12*12"] = "144!",
	["square root of 9"] = "3!",
	["square root of 16"] = "4!",
	["square root of 25"] = "5!",
	["square root of 36"] = "6!",
	["square root of 49"] = "7!",
	["square root of 64"] = "8!",
	["square root of 81"] = "9!",
	["square root of 100"] = "10!",
	["square root of 144"] = "12!",
	["what is pi"] = "Pi (π) is approximately 3.14159. It is the ratio of a circle's circumference to its diameter.",
	["what is the formula for area of a circle"] = "A = πr² (pi times radius squared).",
	["what is the formula for area of a triangle"] = "A = (base × height) / 2.",
	["what is the formula for area of a rectangle"] = "A = length × width.",
	["what is the formula for volume of a cube"] = "V = side³.",
	["what is the formula for volume of a sphere"] = "V = (4/3)πr³.",
	["what is pythagorean theorem"] = "In a right triangle: a² + b² = c².",
	["what is the quadratic formula"] = "x = [-b ± √(b² - 4ac)] / (2a).",
	["what is a prime number"] = "A number greater than 1 that has no positive divisors other than 1 and itself.",
	["is 1 a prime number"] = "No, 1 is not a prime number.",
	["is 2 a prime number"] = "Yes, 2 is the only even prime number.",
	["what is an even number"] = "A number that is divisible by 2 with no remainder.",
	["what is an odd number"] = "A number that is not divisible by 2.",
	["what is a fraction"] = "A number that represents a part of a whole (numerator/denominator).",
	["what is a decimal"] = "A number that uses a decimal point to show values less than one.",
	["what is a percentage"] = "A number or ratio expressed as a fraction of 100.",
	["convert 0.5 to percent"] = "50%.",
	["convert 1/4 to percent"] = "25%.",
	["convert 0.75 to fraction"] = "3/4.",
	["what is the square of 5"] = "25.",
	["what is the square of 8"] = "64.",
	["what is the square of 12"] = "144.",
	["what is the cube of 3"] = "27.",
	["what is the cube of 4"] = "64.",
	["what is 2 to the power of 5"] = "32.",
	["what is 3 to the power of 4"] = "81.",
	["what is 10 to the power of 3"] = "1000.",
	["what is algebra"] = "A branch of mathematics that uses letters and symbols to represent numbers and quantities.",
	["what is geometry"] = "The study of shapes, sizes, relative positions of figures, and properties of space.",
	["what is calculus"] = "The mathematical study of continuous change (derivatives and integrals).",

	-- ===== EDUCATIONAL - HISTORY =====
	["who invented the light bulb"] = "Thomas Edison is widely credited, though many others contributed to its development.",
	["who invented the telephone"] = "Alexander Graham Bell.",
	["who invented the airplane"] = "The Wright brothers (Orville and Wilbur Wright).",
	["who painted the mona lisa"] = "Leonardo da Vinci.",
	["who wrote romeo and juliet"] = "William Shakespeare.",
	["who wrote hamlet"] = "William Shakespeare.",
	["who was the first president of the usa"] = "George Washington.",
	["who was abraham lincoln"] = "The 16th President of the United States who led the country during the Civil War and abolished slavery.",
	["what year did world war 1 start"] = "1914.",
	["what year did world war 2 start"] = "1939.",
	["what year did world war 2 end"] = "1945.",
	["what is the declaration of independence"] = "The document that declared the American colonies independent from Great Britain in 1776.",
	["who wrote the declaration of independence"] = "Primarily Thomas Jefferson.",
	["what is the constitution"] = "The supreme law of the United States of America.",
	["how many amendments does the constitution have"] = "27 amendments.",
	["what is the bill of rights"] = "The first 10 amendments to the U.S. Constitution.",
	["what is democracy"] = "A system of government by the whole population, usually through elected representatives.",
	["what is a republic"] = "A form of government in which power is held by the people and their elected representatives.",

	-- ===== GEN Z SLANG & QUESTIONS =====
	["what is rizz"] = "Rizz means charisma or the ability to attract someone romantically.",
	["rizz"] = "Rizz is short for charisma. You got rizz?",
	["what is sigma"] = "Sigma refers to a lone-wolf type who is independent and successful outside the normal social hierarchy.",
	["sigma"] = "Sigma energy!",
	["what is skibidi"] = "Skibidi comes from the Skibidi Toilet meme series. It's chaotic internet humor.",
	["skibidi"] = "Skibidi dop dop dop yes yes!",
	["what is ohio"] = "In meme culture, 'Ohio' means something weird, cursed, or strange.",
	["ohio"] = "Only in Ohio!",
	["what is gyatt"] = "Gyatt is an expression of surprise, usually at someone's appearance.",
	["gyatt"] = "GYATT!",
	["what is fanum tax"] = "Fanum tax is when someone takes a portion of your food (popularized by streamer Fanum).",
	["fanum tax"] = "That's a classic Fanum tax.",
	["what is aura"] = "Aura refers to the vibe or energy someone gives off.",
	["aura"] = "Your aura is strong!",
	["what is cooked"] = "Cooked means you're done for, messed up, or in a bad situation.",
	["cooked"] = "You're cooked fr.",
	["what is locked in"] = "Locked in means fully focused and determined.",
	["locked in"] = "I'm locked in right now.",
	["what is mid"] = "Mid means average or mediocre.",
	["mid"] = "That's mid.",
	["what is cap"] = "Cap means a lie. 'No cap' means no lie / for real.",
	["cap"] = "That's cap!",
	["no cap"] = "No cap, for real.",
	["what is bussin"] = "Bussin means really good (especially food).",
	["bussin"] = "This is bussin!",
	["what is sus"] = "Sus means suspicious.",
	["sus"] = "That's sus.",
	["what is bet"] = "Bet means okay / agreement / challenge accepted.",
	["bet"] = "Bet!",
	["what is fr"] = "FR means for real.",
	["fr"] = "FR!",
	["what is ong"] = "ONG means on God (I swear / for real).",
	["ong"] = "ONG!",
	["what is lowkey"] = "Lowkey means somewhat / kind of / secretly.",
	["lowkey"] = "Lowkey true.",
	["what is highkey"] = "Highkey means very / obviously / openly.",
	["highkey"] = "Highkey facts.",
	["what is vibe"] = "Vibe means the atmosphere or feeling of something.",
	["vibe"] = "Good vibes only!",
	["what is vibing"] = "Vibing means relaxing and enjoying the moment.",
	["vibing"] = "Just vibing.",
	["what is slay"] = "Slay means to do something extremely well or look amazing.",
	["slay"] = "Slay!",
	["what is periodt"] = "Periodt is a stronger 'period' – end of discussion.",
	["periodt"] = "Periodt!",
	["what is it's giving"] = "It's giving means it has the vibe or energy of something.",
	["its giving"] = "It's giving main character energy.",
	["what is main character"] = "Main character energy means acting like the star of your own story.",
	["main character"] = "Main character vibes!",
	["what is npc"] = "NPC means Non-Player Character – someone who seems basic or follows the crowd.",
	["npc"] = "Don't be an NPC.",
	["what is delulu"] = "Delulu means delusional (usually in a fun, hopeful way).",
	["delulu"] = "Delulu is the solulu!",
	["what is brainrot"] = "Brainrot refers to extremely addictive or low-quality internet content.",
	["brainrot"] = "Peak brainrot.",
	["what is mewing"] = "Mewing is a tongue-posture technique claimed to improve jawline.",
	["mewing"] = "Keep mewing!",
	["what is looksmaxxing"] = "Looksmaxxing means trying to improve your physical appearance as much as possible.",
	["looksmaxxing"] = "Looksmaxxing era.",
	["what is mog"] = "Mog means to look significantly better than someone else.",
	["mog"] = "He mogged everyone.",
	["what is rizzler"] = "A rizzler is someone with a lot of rizz.",
	["rizzler"] = "The Rizzler!",
	["what is sigma male"] = "A sigma male is an independent lone wolf outside the traditional alpha/beta hierarchy.",
	["sigma grindset"] = "Sigma grindset activated.",
	["what is the grind"] = "The grind means working hard and consistently toward your goals.",
	["grind"] = "Stay on the grind.",
	["what is crashed out"] = "Crashed out means lost control or went crazy (usually negatively).",
	["crashed out"] = "He crashed out.",
	["what is tweaking"] = "Tweaking means acting weird or overreacting.",
	["tweaking"] = "Why are you tweaking?",
	["what is yapping"] = "Yapping means talking a lot, often unnecessarily.",
	["yapping"] = "Stop yapping!",
	["what is the ick"] = "The ick is a sudden feeling of repulsion toward someone.",
	["the ick"] = "I got the ick.",
	["what is situationship"] = "A situationship is a romantic/sexual relationship without clear labels.",
	["situationship"] = "Stuck in a situationship.",
	["what is talking stage"] = "The talking stage is when two people are getting to know each other before officially dating.",
	["talking stage"] = "Still in the talking stage.",
	["what is ghosting"] = "Ghosting is suddenly cutting off all communication without explanation.",
	["ghosting"] = "Got ghosted.",
	["what is soft launching"] = "Soft launching is subtly posting about a partner without fully revealing them.",
	["soft launch"] = "Soft launched.",
	["what is hard launching"] = "Hard launching is fully revealing a relationship publicly.",
	["hard launch"] = "Hard launched!",
	["what is be for real"] = "Be for real means be serious / stop joking.",
	["be for real"] = "Be for real right now.",
	["what is so real"] = "So real means very true / relatable.",
	["so real"] = "So real.",
	["what is ate"] = "Ate means did something extremely well ('ate and left no crumbs').",
	["ate"] = "You ate that!",
	["left no crumbs"] = "Left no crumbs!",
	["what is understood the assignment"] = "Understood the assignment means did exactly what was expected, perfectly.",
	["understood the assignment"] = "They understood the assignment.",
	["what is the tea"] = "The tea means the gossip or news.",
	["spilling the tea"] = "Spilling the tea!",
	["what is shade"] = "Shade means subtle disrespect or an insult.",
	["throwing shade"] = "Throwing shade!",
	["what is iconic"] = "Iconic means legendary or extremely memorable.",
	["iconic"] = "Iconic behavior.",
	["what is goated"] = "GOATed means Greatest Of All Time.",
	["goated"] = "You're GOATed!",
	["what is the goat"] = "The GOAT means Greatest Of All Time.",
	["the goat"] = "The GOAT!",
	["what is valid"] = "Valid means acceptable or reasonable.",
	["valid"] = "That's valid.",
	["what is based"] = "Based means being true to yourself and not caring about others' opinions.",
	["based"] = "Based!",
	["what is cringe"] = "Cringe means embarrassing or awkward.",
	["cringe"] = "That's cringe.",
	["what is ratio"] = "Ratio means getting more opposing replies/likes than the original post.",
	["ratioed"] = "Got ratioed.",
	["what is l"] = "L means loss (taking an L).",
	["take the l"] = "Just take the L.",
	["what is w"] = "W means win.",
	["big w"] = "Big W!",
	["dub"] = "That's a dub!",
	["what is lit"] = "Lit means exciting or excellent.",
	["lit"] = "This is lit!",
	["what is fire"] = "Fire means really good / cool.",
	["fire"] = "That's fire!",
	["what is heat"] = "Heat means something really good or impressive.",
	["heat"] = "Pure heat!",
	["what is trash"] = "Trash means really bad.",
	["trash"] = "That's trash.",
	["what is peak"] = "Peak means the best / highest quality.",
	["peak"] = "Peak fiction!",
	["what is s tier"] = "S tier means the absolute best (from ranking systems).",
	["s tier"] = "S tier!",
	["what is a tier"] = "A tier means excellent.",
	["a tier"] = "A tier.",
	["what is touch grass"] = "Touch grass means go outside / get off the internet.",
	["touch grass"] = "Go touch grass!",
	["what is chronically online"] = "Chronically online means spending way too much time on the internet.",
	["chronically online"] = "You're chronically online.",
	["what is irl"] = "IRL means In Real Life.",
	["irl"] = "IRL!",
	["what is afk"] = "AFK means Away From Keyboard.",
	["afk"] = "AFK real quick.",
	["what is fomo"] = "FOMO means Fear Of Missing Out.",
	["fomo"] = "I have FOMO.",
	["what is yolo"] = "YOLO means You Only Live Once.",
	["yolo"] = "YOLO!",
	["what is tbh"] = "TBH means To Be Honest.",
	["tbh"] = "TBH...",
	["what is ngl"] = "NGL means Not Gonna Lie.",
	["ngl"] = "NGL!",
	["what is imo"] = "IMO means In My Opinion.",
	["imo"] = "IMO...",
	["what is btw"] = "BTW means By The Way.",
	["btw"] = "BTW...",
	["what is smh"] = "SMH means Shaking My Head.",
	["smh"] = "SMH.",
	["what is idc"] = "IDC means I Don't Care.",
	["idc"] = "IDC.",
	["what is asap"] = "ASAP means As Soon As Possible.",
	["asap"] = "ASAP!",
	["what is fyi"] = "FYI means For Your Information.",
	["fyi"] = "FYI!",

	-- ===== ROBLOX GENERAL =====
	["what is roblox"] = "Roblox is an online platform and game creation system where users can create and play games made by other users.",
	["roblox"] = "Roblox is awesome!",
	["when was roblox created"] = "Roblox was founded in 2004 and publicly launched in 2006.",
	["who created roblox"] = "David Baszucki and Erik Cassel.",
	["who is the ceo of roblox"] = "David Baszucki.",
	["what is a roblox experience"] = "An experience is what Roblox now calls games on the platform.",
	["what is a roblox place"] = "A place is a specific location or map within an experience.",
	["what is a roblox avatar"] = "Your avatar is the character you customize and use across experiences.",
	["what is robux"] = "Robux is the virtual currency used on Roblox.",
	["how do you get robux"] = "You can buy Robux with real money, earn them from creating popular experiences, selling items, or through Premium payouts.",
	["what is roblox premium"] = "Roblox Premium is a subscription that gives monthly Robux, trading privileges, and other benefits.",
	["what is a game pass"] = "A Game Pass is a one-time purchase that unlocks special features or items in an experience.",
	["what is a developer product"] = "A Developer Product is an item that can be purchased multiple times (like in-game currency packs).",
	["what is a limited item"] = "Limited items are collectible avatar items with a fixed quantity that can be resold.",
	["what is trading"] = "Trading allows Premium members to trade limited items with other players.",
	["what is the catalog"] = "The catalog is where you browse and buy avatar clothing, accessories, and gear.",
	["what is a group"] = "A group is a community on Roblox that can own experiences, clothing, and ranks.",
	["what is an obby"] = "An obby is an obstacle course experience.",
	["what is a simulator"] = "A simulator is a game where you repeatedly perform actions to gain strength, money, or other stats.",
	["what is a tycoon"] = "A tycoon is a game where you build and manage a business or base that generates income.",
	["what is a roleplay game"] = "A roleplay (RP) game lets players act out roles and scenarios together.",
	["what is a fighting game"] = "A fighting game focuses on combat between players or against NPCs.",
	["what is a horror game"] = "A horror game is designed to scare players with atmosphere, tension, and jumpscares.",
	["do you play roblox"] = "I live in Roblox!",
	["favorite roblox game"] = "This one right now!",
	["are you a bot"] = "Yes, an AI bot!",
	["script"] = "I'm made of Lua script!",
	["lua"] = "Lua is a great language for Roblox!",
	["exploit"] = "I don't support exploiting.",
	["hack"] = "No hacking here!",
	["admin"] = "I'm not an admin!",
	["owner"] = "I'm just a chat AI!",

	-- ===== POPULAR ROBLOX GAMES =====
	["what is bedwars"] = "BedWars is a popular Roblox experience similar to Minecraft Bed Wars.",
	["what is adopt me"] = "Adopt Me is a very popular pet adoption and roleplay experience.",
	["what is brookhaven"] = "Brookhaven is a popular roleplay town experience.",
	["what is blox fruits"] = "Blox Fruits is a popular anime-inspired fighting adventure experience.",
	["what is pet simulator"] = "Pet Simulator is a popular simulator where you collect and upgrade pets.",
	["what is arsenal"] = "Arsenal is a popular fast-paced first-person shooter.",
	["what is phantom forces"] = "Phantom Forces is a realistic military-style FPS.",
	["what is jailbreak"] = "Jailbreak is a popular cops-and-robbers experience.",
	["what is murder mystery 2"] = "Murder Mystery 2 is a game where one player is the murderer.",
	["what is doors"] = "Doors is a popular horror experience with multiple rooms and entities.",
	["what is the strongest battlegrounds"] = "The Strongest Battlegrounds is a popular anime fighting experience.",
	["what is deepwoken"] = "Deepwoken is a hardcore fantasy RPG experience.",
	["what is welcome to bloxburg"] = "Welcome to Bloxburg is a life simulation and building experience.",
	["what is royale high"] = "Royale High is a popular dress-up and school roleplay experience.",
	["what is natural disaster survival"] = "Natural Disaster Survival is a classic experience where you survive disasters.",
	["what is work at a pizza place"] = "Work at a Pizza Place is a classic job roleplay experience.",

	-- ===== ROBLOX STUDIO & CODING =====
	["what is roblox studio"] = "Roblox Studio is the free program used to create experiences for Roblox.",
	["how do i open roblox studio"] = "Download it from the Roblox Creator Dashboard or website and open it.",
	["what is a baseplate"] = "A baseplate is the default flat ground template when you create a new place.",
	["what is a spawn location"] = "A SpawnLocation is where players appear when they join or respawn.",
	["what is a part"] = "A Part is a basic building block (block, ball, cylinder, wedge, etc.).",
	["what is a meshpart"] = "A MeshPart is a part that can display a custom 3D mesh.",
	["what is a model"] = "A Model is a container that groups parts and other objects together.",
	["what is a folder"] = "A Folder is used to organize objects in the Explorer.",
	["what is the explorer"] = "The Explorer window shows the hierarchy of all objects in your place.",
	["what is the properties window"] = "The Properties window lets you view and edit attributes of selected objects.",
	["what is the output window"] = "The Output window shows print statements, warnings, and errors from scripts.",
	["what is a script"] = "A Script runs Lua code on the server.",
	["what is a local script"] = "A LocalScript runs Lua code on the client (the player's device).",
	["what is a module script"] = "A ModuleScript holds reusable code that other scripts can require.",
	["what is the difference between script and localscript"] = "Scripts run on the server (trusted). LocalScripts run on the client (can be exploited).",
	["where do scripts go"] = "Server Scripts usually go in ServerScriptService. LocalScripts go in StarterPlayerScripts, StarterCharacterScripts, or Tools.",
	["where do module scripts go"] = "ModuleScripts often go in ReplicatedStorage or ServerStorage so multiple scripts can require them.",
	["what is replicatedstorage"] = "ReplicatedStorage holds objects accessible by both the server and clients.",
	["what is serverstorage"] = "ServerStorage holds objects only the server can access (good for security).",
	["what is serverscriptservice"] = "ServerScriptService is the recommended place for most server-side Scripts.",
	["what is startergui"] = "StarterGui holds GUI objects that are copied into each player's PlayerGui when they join.",
	["what is starterpack"] = "StarterPack holds Tools that are copied into each player's Backpack.",
	["what is starterplayer"] = "StarterPlayer contains player-related settings and script containers.",
	["what is starterplayerscripts"] = "StarterPlayerScripts holds LocalScripts that run for each player when they join.",
	["what is startercharacterscripts"] = "StarterCharacterScripts holds LocalScripts that run every time a character spawns.",
	["what is workspace"] = "Workspace contains all the visible 3D objects and parts in the game world.",
	["what is lighting"] = "Lighting controls the sky, atmosphere, shadows, brightness, and time of day.",
	["what is tween service"] = "TweenService smoothly animates properties of objects over time.",
	["what is userinputservice"] = "UserInputService detects keyboard, mouse, touch, and gamepad input.",
	["what is runservice"] = "RunService provides events that fire every frame (Heartbeat, RenderStepped, Stepped).",
	["what is players"] = "The Players service manages all players currently in the game.",
	["what is debris"] = "Debris is used to safely destroy objects after a delay.",
	["what is collectionservice"] = "CollectionService lets you tag instances and work with groups of tagged objects.",
	["what is pathfindingservice"] = "PathfindingService calculates paths for NPCs around obstacles.",
	["what is datastoreservice"] = "DataStoreService is used to save and load permanent player data.",
	["what is a remoteevent"] = "A RemoteEvent sends signals between the client and the server (one-way).",
	["what is a remotefunction"] = "A RemoteFunction sends a request and waits for a return value (two-way).",
	["what is the difference between remoteevent and remotefunction"] = "RemoteEvent is fire-and-forget. RemoteFunction yields until it gets a response.",
	["what is filtering enabled"] = "FilteringEnabled (always on now) means the client cannot freely change the game for others – important logic must run on the server.",
	["what is client sided"] = "Client-sided means the code runs only on the player's device (can be exploited).",
	["what is server sided"] = "Server-sided means the code runs on Roblox servers and is much more secure.",
	["why is server sided better"] = "Server-sided logic cannot be easily exploited by the client.",
	["what is a free model"] = "A free model is a model uploaded by other users that you can insert (always check for viruses/backdoors).",
	["what is a toolbox"] = "The Toolbox in Studio contains free models, scripts, audio, images, and plugins.",
	["what is a backdoor"] = "A backdoor is hidden malicious code that can give someone control of your game.",
	["how do i check free models"] = "Open the model, look for suspicious Scripts, and delete anything you don't understand or need.",

	-- ===== SIMPLE CODING HOW-TOs =====
	["how do i make a part change color"] = "part.Color = Color3.fromRGB(255, 0, 0)  or  part.BrickColor = BrickColor.new('Really red')",
	["how do i make a part transparent"] = "part.Transparency = 0.5  (0 = fully visible, 1 = invisible)",
	["how do i make a part anchored"] = "part.Anchored = true",
	["how do i make a part cancollide false"] = "part.CanCollide = false",
	["how do i teleport a player"] = "character:PivotTo(CFrame.new(x, y, z))  or  humanoidRootPart.CFrame = CFrame.new(x, y, z)",
	["how do i change walkspeed"] = "humanoid.WalkSpeed = 32  (default is 16)",
	["how do i make a player jump higher"] = "humanoid.JumpPower = 100  (or use JumpHeight on newer humanoids)",
	["how do i make a gui appear"] = "Set the ScreenGui.Enabled = true  or  Frame.Visible = true",
	["how do i make a button do something"] = "button.MouseButton1Click:Connect(function() print('Clicked!') end)",
	["how do i detect when a player joins"] = "game.Players.PlayerAdded:Connect(function(player) print(player.Name .. ' joined') end)",
	["how do i detect when a player leaves"] = "game.Players.PlayerRemoving:Connect(function(player) print(player.Name .. ' left') end)",
	["how do i detect when a character spawns"] = "player.CharacterAdded:Connect(function(character) ... end)",
	["how do i get the local player"] = "In a LocalScript: local player = game.Players.LocalPlayer",
	["how do i get a player's character"] = "local character = player.Character or player.CharacterAdded:Wait()",
	["how do i get the humanoid"] = "local humanoid = character:WaitForChild('Humanoid')",
	["how do i get the humanoidrootpart"] = "local hrp = character:WaitForChild('HumanoidRootPart')",
	["how do i make a simple print script"] = "print('Hello World!')",
	["how do i make a kill brick"] = "Connect to part.Touched. When a character touches it, get the Humanoid and set Health = 0. Use a debounce!",
	["how do i make leaderstats"] = "Create a Folder named 'leaderstats' inside the player, then put IntValues or StringValues inside it.",
	["how do i save data"] = "Use DataStoreService:GetDataStore('Name'):SetAsync(key, value) on the server.",
	["how do i load data"] = "Use DataStoreService:GetDataStore('Name'):GetAsync(key) on the server.",
	["how do i kick a player"] = "player:Kick('Reason here')  -- must be done on the server",
	["how do i make a simple day night cycle"] = "Use a loop or RunService to slowly change Lighting.ClockTime.",
	["how do i make a door that opens"] = "Use TweenService to tween the door's CFrame or position when a ProximityPrompt is triggered.",
	["how do i make a tool"] = "Create a Tool, put a Part named 'Handle' inside it, then add a LocalScript or Script for behavior.",
	["how do i detect tool activation"] = "tool.Activated:Connect(function() ... end)",
	["how do i make a proximity prompt"] = "Insert a ProximityPrompt into a part. Connect to ProximityPrompt.Triggered.",
	["how do i make a click detector"] = "Insert a ClickDetector into a part. Connect to ClickDetector.MouseClick.",
	["how do i use waitforchild"] = "local obj = parent:WaitForChild('ChildName')  -- yields until the child exists",
	["how do i use findfirstchild"] = "local obj = parent:FindFirstChild('ChildName')  -- returns nil if not found",
	["how do i make a debounce"] = "local debounce = false\nif not debounce then\n  debounce = true\n  -- do something\n  task.wait(1)\n  debounce = false\nend",
	["how do i make a cooldown"] = "Store the last time an action happened and check if enough time has passed before allowing it again.",
	["what is a vector3"] = "Vector3 represents a 3D value with X, Y, Z components (position or direction).",
	["what is a cframe"] = "CFrame represents both position and rotation in 3D space.",
	["what is a color3"] = "Color3 represents an RGB color (values from 0 to 1, or use fromRGB 0-255).",
	["what is a udim2"] = "UDim2 is used for GUI size and position (combines scale and offset).",
	["what is task.wait"] = "task.wait(seconds) yields the current thread for the given time (preferred over wait()).",
	["what is task.spawn"] = "task.spawn(function) runs a function in a new thread without yielding the current one.",
	["what is task.delay"] = "task.delay(seconds, function) waits the given time then runs the function.",
	["what is pcall"] = "pcall(function) runs code in protected mode and returns success + result/error.",
	["what is pairs"] = "pairs(table) iterates over all key-value pairs in a table.",
	["what is ipairs"] = "ipairs(table) iterates over array-like indexes in order.",
	["what is a table"] = "A table is Lua's main data structure – used for both arrays and dictionaries.",
	["what is a function"] = "A function is a reusable block of code that can take parameters and return values.",
	["what is print"] = "print(...) outputs values to the Output window.",
	["what is warn"] = "warn(...) outputs a yellow warning message to the Output window.",

	-- ===== MORE COMMON / RANDOM =====
	["what"] = "What?",
	["why"] = "Why not?",
	["how"] = "How what?",
	["when"] = "When what?",
	["where"] = "Where what?",
	["who"] = "Who?",
	["really"] = "Really!",
	["seriously"] = "Seriously!",
	["wow"] = "Wow!",
	["omg"] = "OMG!",
	["oh"] = "Oh!",
	["ah"] = "Ah!",
	["hmm"] = "Hmm...",
	["huh"] = "Huh?",
	["nice"] = "Nice!",
	["cool"] = "Cool!",
	["awesome"] = "Awesome!",
	["amazing"] = "Amazing!",
	["great"] = "Great!",
	["good"] = "Good!",
	["bad"] = "Sorry to hear that.",
	["boring"] = "Sorry, want to talk about something else?",
	["interesting"] = "Glad you think so!",
	["test"] = "Test successful!",
	["testing"] = "I hear you loud and clear!",
	["ping"] = "Pong!",
	["pong"] = "Ping!",
	["hello world"] = "Hello World!",
	["you are cool"] = "Thanks, you're cool too!",
	["you're cool"] = "Appreciate it!",
	["you are awesome"] = "Aww thank you!",
	["you're awesome"] = "You're awesome too!",
	["you are the best"] = "You're the best!",
	["you're the best"] = "Thanks a lot!",
	["compliment me"] = "You're awesome!",
	["say something nice"] = "You're a great person!",
	["encourage me"] = "You can do it!",
	["motivate me"] = "Keep going, you're doing great!",
	["cheer me up"] = "You got this! Smile!",
	["make me happy"] = "You're amazing just the way you are!",
	["any advice"] = "Be kind to yourself and keep learning!",
	["advice"] = "Stay positive and take things one step at a time.",
	["tip"] = "Drink water and take breaks!",
}

local function addMsg(text)
	local Msg = Instance.new("TextLabel")
	Msg.Size = UDim2.new(1, -10, 0, 35)
	Msg.BackgroundColor3 = Color3.fromRGB(30, 50, 100)
	Msg.TextColor3 = Color3.fromRGB(255, 255, 255)
	Msg.Font = Enum.Font.Gotham
	Msg.TextSize = 13
	Msg.TextWrapped = true
	Msg.Text = text
	Msg.TextXAlignment = Enum.TextXAlignment.Left
	Msg.Parent = Chat

	local MsgCorner = Instance.new("UICorner")
	MsgCorner.CornerRadius = UDim.new(0, 6)
	MsgCorner.Parent = Msg

	-- Update canvas size so scrolling works
	Chat.CanvasSize = UDim2.new(0, 0, 0, Layout.AbsoluteContentSize.Y + 10)
	Chat.CanvasPosition = Vector2.new(0, math.max(0, Chat.CanvasSize.Y.Offset - Chat.AbsoluteSize.Y))
	return Msg
end

-- Keep canvas size updated when layout changes
Layout:GetPropertyChangedSignal("AbsoluteContentSize"):Connect(function()
	Chat.CanvasSize = UDim2.new(0, 0, 0, Layout.AbsoluteContentSize.Y + 10)
end)

Input.FocusLost:Connect(function(enter)
	if enter and Input.Text ~= "" then
		local userText = Input.Text
		addMsg("You: " .. userText)

		local Typing = addMsg("Ai: Typing...")
		local lowerText = string.lower(userText)
		local Reply = Responses[lowerText] or "I don't know that one. Try asking something else!"

		task.delay(0.8, function()
			if Typing and Typing.Parent then
				Typing.Text = "Ai: " .. Reply
			end
		end)

		Input.Text = ""
	end
end)
